### ISSUE TITLE
SDKCODE:1006

### ISSUE THREAD

**Issue by trondhindenes** [harness/ff-python-server-sdk#99]
We're seeing this on some of our pods:

SDKCODE:1006: The SDK has failed to initialize and defaults will be served, reason: RetrievalError: Failed to retrieve segments ''NoneType' object is not iterable'

From what I can see the client still gets initialized. How can we check programmatically if this happens?

**Comment by trondhindenes** [comment]
I checked the status page for Harness, but it was all green. Would be good if issues like that was surfaced on the status page (I'd actually go as far as saying it's absolutely necessary that the status page is kept updated)

**Comment by erdirowlands** [comment]
You're absolutely right - I'm not sure why it hasn't been placed there.  Thank you for checking the status page and apologies you've had to raise an issue when it was green. I'll speak with the team and see what went wrong with the status page getting updated.

**Comment by erdirowlands** [comment]
I'll mark the issue as closed in the time being.

**Comment by erdirowlands** [comment]
Hi @trondhindenes we have updated the page with more information. https://status.harness.io/incidents/cby168cv3lxx 

Apologies for the delay getting that posted.
